export default {
  login: 'login',
  logout: 'logout',
  refreshToken: 'refresh-token',
  sendOtp: 'sent-otp',
  verifyOtp: 'verify-otp',
  attributesSetter: 'attributes-setter-data',
  donerProfile: 'doner-profile-details',
  getGallery: 'get-gallery',
  deleteGallery: 'delete-gallery',
  getProfileMatches: 'get-profile-matches',
  preferencesAgeRangeData: 'preferences-age-range-data',
  preferencesSetterData: 'preferences-setter-data',
  profileMatchRequest: 'profile-match-request',
  profileRegister: 'profile-register',
  profileSetterData: 'profile-setter-data',
  ptbProfileCard: 'ptb-profile-card',
  ptbProfileDetails: 'ptb-profile-details',
  setAttributes: 'set-attributes',
  setGallery: 'set-gallery',
  setPreferences: 'set-preferences',
  states: 'states',
  registerDevice: 'register-device',
  parentsMatchedDoner: 'parents-matched-doner',
  createSubscription: 'create-subscription',
  subscriptionPlan: 'subscription-plan',
  subscriptionStatus: 'subscription-status',
  register: 'register',
  profile_setter_data: 'profile-setter-data',
  preference_setter_data: 'preferences-setter-data',
  get_attributes: 'attributes-setter-data',
  ptb_profile_card: 'ptb-profile-card',
  ptb_profile_details: 'ptb-profile-details',
  get_gallery: 'get-gallery',
  parents_matched_doner: 'parents-matched-doner',
  doner_profile_details: 'doner-profile-details',
  update_profile_img: 'update-profile-pic',
  profile_match_request: 'profile-match-request',
  enquiry: 'enquiry',
  userType: 'roles',
  profile_match_request_response: 'profile-match-request-response',
  chat_feedback: 'chat-feedback',
  push_notification: 'send-push-notification',
  delete_account: 'delete-account',
  message:'/Messages/',
  verifyEmail:'/v1/verify-email',
  send_verification_mail:'/v1/send-verification-mail',
  change_password: 'change-password',
  resetPassword: 'reset-password',
  get_user_detail: 'get-user-profile',
  update_user_detail: 'update-profile',
  message: '/Messages/',
};
