export const ValidationMessages = {
  MOBILE_REQUIRED: 'Mobile number is a required feild.',
  PASSWORD_REQUIRED: 'Password is a required feild.',
  COMMON_REQUIRED: 'This is a required feild.',
  INVALID_MOBILE: 'Mobile number is not valid.',
  PICTURE_REQUIRE: 'Please add Profile Photo',
  TERMS_OF_USE: 'Please accept the Terms of Use',
  FIRST_NAME: 'Please enter your First Name',
  LAST_NAME: 'Please enter your Last Name',
  EMPTY_EMAIL: 'Please enter your Email ID',
  INVALID_EMAIL: 'Please enter a valid Email ID',
  PASSWORD: 'Please Set the Password',
  CONFIRM_PASSWORD: 'Please enter Confirm Password',
  ADD_PROFILE_PHOTO: 'Please add Profile Photo',
  DOB: 'Please enter your Date of Birth',
  ENTER_DOB:'Please enter your DOB',
  ENTER_GENDER:'Please select your Gender',
  ENTER_SEXUAL_ORIENTATION:'Please select your Sexual Orientation',
  ENTER_RELATIONSHIP:'Please select your Relationship Status',
  ENTER_STATE:'Please select your State',
  ENTER_ZIP:'Please enter your Zip Code',
  ENTER_BIO:'Please enter your Bio',
  UNMATCHED_PASS: 'Password Does not matched',
  RACE: 'Please select your race preference',
  SELECT_LOOKING: 'Please select whom you are looking for',
  SELECT_HAIR: 'Please select your hair color preference',
  SELECT_EYE: 'Please select your eye color preference',
  SELECT_HEIGHT: 'Please select your height',
  SELECT_AGE: 'Please select your age',
  SELECT_ETHNICITY: 'Please select your ethnicity preference',
  MOBILE_REQUIRED: 'Mobile number is a required feild!',
  PASSWORD_REQUIRED: 'Password is a required feild!',
  COMMON_REQUIRED: 'This is a required feild!',
  INVALID_MOBILE: 'Mobile number is not valid!',
  // PASSWORD_MIN: 'Must have minimum 8 characters',
  PASSWORD_MIN: 'Minimum 8 characters',
  // SPECIAL_CHAR: 'Must have atleast 1 special character',
  SPECIAL_CHAR: 'Atleast 1 special character',
  ALPHA_NUM: 'Must be Alphanumeric',
  INVALID_OTP: 'OTP is not valid',
  LOCATION: 'Please select your Location preference',
  RACE: 'Please select your race preference',
  MAX_FIRST_NAME: 'First name must be at most 30 characters',
  MAX_MIDDLE_NAME: 'Middle name must be at most 30 characters',
  MAX_LAST_NAME: 'Last name must be at most 30 characters',
  Education:'Please select your Education preference',
  MAX_ZIP:'Zip code can be of 5 digits only',
  MIN_ZIP:'Zip code should be of 5 digits',
  SELECT_RACE:'Please enter Race',
  SELECT_MOT_ETHNICITY:"Please enter Mother's Ethnicity",
  SELECT_FAT_ETHNICITY: "Please provide Father's Ethnicity",
  SELECT_HEIGHT:'Please enter Height',
  SELECT_EDUCATION:"Please select your maximum Education Qualification",
  SELECT_HAIR:'Please enter Hair color',
  SELECT_EYE:'Please enter Eye color',
  SELECT_WEIGHT:'Please enter Weight',
  CAPSLOCK:'Atleast 1 upper case letter',
  OTP_REQUIRED:'Required!'
  




};
export default {
  landing: {
    LOG_IN: 'LOG IN',
    REGISTER: 'REGISTER',
    Like_Match_Connect: 'Like, Match & Connect!',
    AboutUs: 'About Us',
    InquiryForm: 'Inquiry Form',
  },
  login: {
    MobileNumber: 'Mobile Number',
    Password: 'Password',
    LOG_IN: 'LOG IN',
    ForgotPassword: 'Forgot Your Password?',
    NewUser: 'New User? Register Now',
  },
  mobile: {
    AccountVerification: 'Account Verification',
    BeforProceed: 'Before we proceed,',
    VerifyNumber: 'please verify your number',
    Code: 'Code',
    MobileNumber: 'Mobile Number',
    VERIFY: 'VERIFY',
  },
  profile: {
    makeAccountFor: 'Make Account For',
    parentToBe: 'Parent To Be',
    uploadImage: '  Upload Display Picture',
    FirstName: 'First Name',
    MiddleName: 'Middle Name (Optional)',
    LastName: 'Last Name',
    EmailAddress: 'Email Address',
    DateOfBirth: 'Date Of Birth',
    setPassword: 'Set Password',
    confirmPassword: 'Confirm Password',
    RegisterAs: 'Register as Surrogate Mother or a Donor',
    Register: 'REGISTER',
    ModalHeader: 'Cancel Registration?',
    ModalSubheader: 'If you cancel now, your progress will be lost.',
    ModalOption1: 'Yes, Discard',
    ModalOption2: 'Stay on Page',
    tmc1: "By continuing, you agree to HERA's ",
    tmc2: 'Terms of use',
    tmc3: 'Privacy Policy',
  },
  preference: {
    setPreference: 'Set Preference',
    filter: 'Filter your search criteria',
    surrogateMother: 'Surrogate Mother',
    EggDonor: 'Egg Donor',
    SpermDonor: 'Sperm Donor',
    lookingFor: 'Who are you looking for?',
    Save: 'SAVE',
    Ethnicity: 'Ethnicity',
    Race: 'Race',
    Location: 'Location',
    AgeRange: 'Age Range',
    Height: 'Height',
    HairColor: 'Hair Color',
    EyeColor: 'Eye Color',
    InquiryForm: 'Inquiry Form',
    About: 'About HERA',
    Logout: 'Log Out',
    yrs: 'yrs',
    Education:'Education'

  },
  otp: {
    title: 'Verify your mobile',
    subtitle1: 'Enter the 6-digit verification',
    subtitle2: 'code sent to your number',
    Btn: 'Submit',
    Trouble: 'Trouble recieving code?',
    SendAgain: 'Send Again',
  },
  sm_register: {
    uploadImage:'Upload Display Picture',
    FirstName: 'First Name',
    MiddleName: 'Middle Name (Optional)',
    LastName: 'Last Name',
    DOB: 'Date Of Birth',
    email: 'Email Address',
    Password: 'Set Password',
    Confirm: 'Confirm Password',
    Title: 'Make account for',
    Btn: 'Register',
  },
  sm_basic: {
    Title: 'Basic Details',
    Subtitle: 'Complete Your Profile',
    Gender: 'Gender',
    Male: 'Male',
    Female: 'Female',
    Other: 'Other',
    Country: 'Country',
    State: 'State',
    Zip: 'Zip Code',
    Occupation: 'Occupation (Optional)',
    SexualOrientation: 'Sexual Orientation',
    RelationshipStatus: 'Relationship Status',
    Bio: 'Add a Short Bio (Max 250 Char)',
    Btn: 'Save Profile',

  },
  sm_set_attributes: {
    Title: 'SET ATTRIBUTES',
    Subtitle: 'Tell us about you',
    Height: 'Height',
    Race: 'Race',
    MotherEthnicity: 'Mother’s Ethnicity',
    FatheEthnicity: 'Father’s Ethnicity',
    Weight: 'Weight',
    EyeColor: 'Eye Color',
    HairColor: 'Hair Color',
    Education: 'Education',
    Btn: 'Save',
  },
  sm_create_gallery: {
    Title: 'Create your gallery',
    Subtitle1: 'To match with a parent,',
    Subtitle2: 'upload photos that speak',
    Subtitle3: 'about you!',
    Btn: 'Go to dashboard'
  },
  bottomSheet:{
    Inquiry_Form:'Inquiry Form',
    About_HERA:'About HERA',
    Log_Out:'Log Out',
  },
  dashboard:{
    Title:'Like, Match & Connect!',
    Subtitle:'Your match might just\n be a click away!',
    locationText:'U S A',
    code:'#SD5882',
    donerAge:'Sperm Doner, 27 yrs',

  },
  bottomSheet: {
    Inquiry_Form: 'Inquiry Form',
    About_HERA: 'About HERA',
    Log_Out: 'Log Out',
  },
  dashboard: {
    Title: 'Like, Match & Connect!',
    Subtitle: 'Your match might just\n be a click away!',
    locationText: 'U S A',
    code: '#SD5882',
    donerAge: 'Sperm Donor, 27 yrs',
    Btn: 'Save',
    Sorry: 'Sorry!',
    Para1:
      'We tried to find the best matches for you but seems like no one is around.',
    Para2: 'May be try again later or change your\n settings.',
  },
  sm_dashboard: {
    Title: 'Like , Match & Connect!',
    Subtitle1: 'Your match might just',
    Subtitle2: 'be a click away!',
  },
  PTB_Profile: {
    State: 'USA',
    first_name: 'Meryl',
    second_name: 'Anderson',
    type: 'Parent to be',
    age: '29',
    yrs: 'yrs',
    bio: 'I give priority to health and play wide range of sports. I have a good exposure to different cultures of the world. I value the donations programmes & every parent who need support ',
    profileHighlits: ['Female', 'Hetrosexual', 'Married'],
    send_request: 'SEND REQUEST',
    request_sent: 'REQUEST SENT',
    request_decline: 'REQUEST DECLINED',
    send_msg: 'SEND MESSAGE',
    video_text: 'Parant has uploaded a sort clip',
  },
  donorPofile: {
    Age: 'Age: ',
    ageDetail: '29 yrs',
    Height: 'Height: ',
    heightDetail: '5 ft 9 in',
    Weight: 'Weight: ',
    weightDetail: '140 pounds',
    Education: 'Education: ',
    educationDetail: 'MFA',
    Occupation: 'Occupation: ',
    ocupationDetail: 'Data Analyst',
    donerDescription: `I give priority to health and play a wide range of sports. I have a good exposure to different cultures of the world. I value the donation programmes & every parent who needs support.`,
    nativePlace:'Native American',
    fatherPlace:'Father is Native American',
    motherPlace:'Mother is Native American',
    hairColor:'Black Hair Color',
    eyeColor:'Amber Eye Color',
    shortClip:'Donor has uploaded a short clip',
    place:'Kentucky',
    code:'#SD5882',
    donerType:'Sperm Donor',
    like_this_profile:' LIKE THIS PROFILE',
    Not_interested:'NOT INTERESTED'
  },
  search_Bar: {
    search: 'Search',
  },
  smSetting:{
    profile: 'Profile',
    ProfileName:'Erica Smith',
    EditAttribute:'Edit Attributes',
    Gallery:'Create a Gallery',
    EditProfile:'Edit Profile',
    Settings:'Settings',
    Inquiry:'Inquiry Form',
    AboutUs:'About Us',
    Btn:'LOG OUT',
    AppVersion:'App Version 0.5'
  }
};
