export const SET_THEME = 'SET_THEME';
export const LOADING_SPINNER = 'LOADING_SPINNER';
export const DISPATCH_LAT_LONG = 'DISPATCH_LAT_LONG';
export const DISPATCH_CURRENT_LOCATION = 'DISPATCH_CURRENT_LOCATION';
/**
 * Auth
 */
export const AUTH_CHECK = 'AUTH_CHECK';

export const AUTH_LOG_IN = 'AUTH_LOG_IN';
export const AUTH_LOG_IN_SUCCESS = 'AUTH_LOG_IN_SUCCESS';
export const AUTH_LOG_IN_FAIL = 'AUTH_LOG_IN_FAIL';

///Device Register
export const DEVICE_REGISTER = 'DEVICE_REGISTER';
export const DEVICE_REGISTER_SUCCESS = 'DEVICE_REGISTER_SUCCESS';
export const DEVICE_REGISTER_FAIL = 'DEVICE_REGISTER_FAIL';

export const GET_GALLERY = 'GET_GALLERY';
export const GET_GALLERY_SUCCESS = 'GET_GALLERY_SUCCESS';
export const GET_GALLERY_FAIL = 'GET_GALLERY_FAIL';

// PTBDASHBOARD
export const PTB_DASHBOARD = 'PTB_DASHBOARD';
export const PTB_DASHBOARD_SUCCESS = 'PTB_DASHBOARD_SUCCESS';
export const PTB_DASHBOARD_FAIL = 'PTB_DASHBOARD_FAIL';

export const PTB_PROFILE_DETAIL = 'PTB_PROFILE_DETAIL';
export const PTB_PROFILE_DETAI_SUCCESS = 'PTB_PROFILE_DETAIL_SUCCESS';
export const PTB_PROFILE_DETAI_FAIL = 'PTB_PROFILE_DETAIL_FAIL';

export const AUTH_MOBILE_NUMBER = 'AUTH_MOBILE_NUMBER';
export const AUTH_MOBILE_NUMBER_SUCCESS = 'AUTH_MOBILE_NUMBER_IN_SUCCESS';
export const AUTH_MOBILE_NUMBER_FAIL = 'AUTH_MOBILE_NUMBER_FAIL';
export const AUTH_MOBILE_NUMBER_RESET = 'AUTH_MOBILE_NUMBER_RESET';

export const AUTH_VERIFY_OTP = 'AUTH_VERIFY_OTP';
export const AUTH_VERIFY_OTP_SUCCESS = 'AUTH_VERIFY_OTP_SUCCESS';
export const AUTH_VERIFY_OTP_FAIL = 'AUTH_VERIFY_OTP_FAIL';

export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
export const AUTH_LOG_OUT_SUCCESS = 'AUTH_LOG_OUT_SUCCESS';
export const AUTH_LOG_OUT_FAIL = 'AUTH_LOG_OUT_FAIL';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';

/**
 * SAVE BASIC DETAIL
 */
export const SAVE_BASIC_DETAIL = 'SAVE_BASIC_DETAIL';
export const SAVE_BASIC_DETAIL_SUCCESS = 'SAVE_BASIC_DETAIL_SUCCESS';
export const SAVE_BASIC_DETAIL_FAIL = 'SAVE_BASIC_DETAIL_FAIL';

/**
 * INQUIRY FORM
 */

export const SUPPORT_FORM = 'SUPPORT_FORM';
export const SUPPORT_FORM_SUCCESS = 'SUPPORT_FORM_SUCCESS';
export const SUPPORT_FORM_FAIL = 'SUPPORT_FORM_FAIL';

/**
 * GET USER TYPE
 */

export const GET_USER_TYPE = 'GET_USER_TYPE';
export const GET_USER_TYPE_SUCCESS = 'GET_USER_TYPE_SUCCESS';
export const GET_USER_TYPE_FAIL = 'GET_USER_TYPE_FAIL';

/**
 * GET STATES
 */
export const GET_STATES_DETAIL = 'GET_STATES_DETAIL';
export const GET_STATES_SUCCESS = 'GET_STATES_SUCCESS';
export const GET_STATES_FAIL = 'GET_STATES_FAIL';
/**
 * GET PROFILE SETTER
 */
export const GET_PROFILE_SETTER_DETAIL = 'GET_PROFILE_SETTER_DETAIL';
export const GET_PROFILE_SETTER_SUCCESS = 'GET_PROFILE_SETTER_SUCCESS';
export const GET_PROFILE_SETTER_FAIL = 'GET_PROFILE_SETTER_FAIL';

/**
 * SET PREFERENCE
 */
export const SET_PREFERENCE = 'SET_PREFERENCE';
export const SET_PREFERENCE_SUCCESS = 'SET_PREFERENCE_SUCCESS';
export const SET_PREFERENCE_FAIL = 'SET_PREFERENCE_FAIL';

/**
 * Get Preference
 */
export const GET_PREFERENCE = 'GET_PREFERENCE';
export const GET_PREFERENCE_SUCCESS = 'GET_PREFERENCE_SUCCESS';
export const GET_PREFERENCE_FAIL = 'GET_PREFERENCE_FAIL';

export const SET_USER = 'SET_USER';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_FAIL = 'SET_USER_FAIL';

/**
 * SAVE PREFERENCE
 */
export const SAVE_PREFERENCE = 'SAVE_PREFERENCE';
export const SAVE_PREFERENCE_SUCCESS = 'SAVE_PREFERENCE_SUCCESS';
export const SAVE_PREFERENCE_FAIL = 'SAVE_PREFERENCE_FAIL';

/**
 * SEXUAL ORIENTATION
 */

export const GET_SEXUAL_ORIENTATION = 'GET_SEXUAL_ORIENTATION';
export const GET_SEXUAL_ORIENTATION_SUCCESS = 'GET_SEXUAL_ORIENTATION_SUCCESS';
export const GET_SEXUAL_ORIENTATION_FAIL = 'GET_SEXUAL_ORIENTATION_FAIL';

/**
 * DONOR PROFILE
 */

export const GET_DONOR_PROFILE_DETAIL = 'GET_DONOR_PROFILE_DETAIL';
export const GET_DONOR_PROFILE_SUCCESS = 'GET_DONOR_PROFILE_SUCCESS';
export const GET_DONOR_PROFILE_FAIL = 'GET_DONOR_PROFILE_FAIL';

/**
 * GET ATTRIBUTE
 */

export const GET_ATTRIBUTE = 'GET_ATTRIBUTE';
export const GET_ATTRIBUTE_SUCCESS = 'GET_ATTRIBUTE_SUCCESS';
export const GET_ATTRIBUTE_FAIL = 'GET_ATTRIBUTE_FAIL';

/**
 * GET USER ATTRIBUTE
 */

export const GET_USER_ATTRIBUTE = 'GET_USER_ATTRIBUTE';
export const GET_USER_ATTRIBUTE_SUCCESS = 'GET_USER_ATTRIBUTE_SUCCESS';
export const GET_USER_ATTRIBUTE_FAIL = 'GET_USER_ATTRIBUTE_FAIL';
/**
 *  DELETE GALLERY
 */

export const GET_DELETE_GALLERY = 'GET_DELETE_GALLERY';
export const GET_DELETE_GALLERY_SUCCESS = 'GET_DELETE_GALLERY_SUCCESS';
export const GET_DELETE_GALLERY_FAIL = 'GET_DELETE_GALLERY_FAIL';

/**
 * DELETE ACCOUNT
 */

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL';

/**
 * SAVE ATTRIBUTE
 */

export const SAVE_ATTRIBUTE = 'SAVE_ATTRIBUTE';
export const SAVE_ATTRIBUTE_SUCCESS = 'SAVE_ATTRIBUTE_SUCCESS';
export const SAVE_ATTRIBUTE_FAIL = 'SAVE_ATTRIBUTE_FAIL';

/**
 * DONOR DASHBOARD
 */

export const DONOR_DASHBOARD = 'DONOR_DASHBOARD';
export const DONOR_DASHBOARD_SUCCESS = 'DONOR_DASHBOARD_SUCCESS';
export const DONOR_DASHBOARD_FAIL = 'DONOR_DASHBOARD_FAIL';

/**
 * PTB DETAILS
 */

export const PTB_DETAIL = 'PTB_DETAIL';
export const PTB_DETAIL_SUCCESS = 'PTB_DETAIL_SUCCESS';
export const PTB_DETAIL_FAIL = 'PTB_DETAIL_FAIL';

/**
 * SM DONOR DETAILS
 */

export const SM_DONOR_DETAIL = 'SM_DONOR_DETAIL';
export const SM_DONOR_DETAIL_SUCCESS = 'SM_DONOR_DETAIL_SUCCESS';
export const SM_DONOR_DETAIL_FAIL = 'SM_DONOR_DETAIL_FAIL';

/**
 * UPDATE PROFILE
 */

export const UPDATE_PROFILE_IMG = 'UPDATE_PROFILE_IMG';
export const UPDATE_PROFILE_IMG_SUCCESS = 'UPDATE_PROFILE_IMG_SUCCESS';
export const UPDATE_PROFILE_IMG_FAIL = 'UPDATE_PROFILE_IMG_FAIL';

/**
 * UPDATE PROFILE
 */

export const SEND_LIKE_PTB = 'SEND_LIKE_PTB';
export const SEND_LIKE_PTB_SUCCESS = 'SEND_LIKE_PTB_SUCCESS';
export const SEND_LIKE_PTB_FAIL = 'SEND_LIKE_PTB_FAIL';

/**
 * CREATE AND GET  SUBSCRIPTION
 */

export const CREATE_SUBSCRIPTION = 'CREATE_SUBSCRIPTION';
export const SUBSCRIPTION_PLAN = 'SUBSCRIPTION_PLAN';
export const SUBSCRIPTION_STATUS = 'SUBSCRIPTION_STATUS';
export const UPDATE_SUBSCRIPTION_STATUS = 'UPDATE_SUBSCRIPTION_STATUS';

export const CREATE_SUBSCRIPTION_SUCCESS = 'CREATE_SUBSCRIPTION_SUCCESS';
export const CREATE_SUBSCRIPTION_FAIL = 'CREATE_SUBSCRIPTION_FAIL';

export const SUBSCRIPTION_PLAN_SUCCESS = 'SUBSCRIPTION_PLAN_SUCCESS';
export const SUBSCRIPTION_PLAN_FAIL = 'SUBSCRIPTION_PLAN_FAIL';

export const SUBSCRIPTION_STATUS_SUCCESS = 'SUBSCRIPTION_STATUS_SUCCESS';
export const SUBSCRIPTION_STATUS_FAIL = 'SUBSCRIPTION_STATUS_FAIL';

/**
 * Profile Match
 */

export const PROFILE_MATCH = 'PROFILE_MATCH';
export const PROFILE_MATCH_SUCCESS = 'PROFILE_MATCH_SUCCESS';
export const PROFILE_MATCH_FAIL = 'PROFILE_MATCH_FAIL';
/**
 * Profile Match Response
 */
export const PROFILE_MATCH_RESPONSE = 'PROFILE_MATCH_RESPONSE';
export const PROFILE_MATCH_RESPONSE_SUCCESS = 'PROFILE_MATCH_RESPONSE_SUCCESS';
export const PROFILE_MATCH_RESPONSE_FAIL = 'PROFILE_MATCH_RESPONSE_FAIL';
/**
 * CHAT
 */
export const PREPEND_CHAT = 'PREPEND_CHAT';
export const APPEND_CHAT = 'APPEND_CHAT';
export const EMPTY_CHAT = 'EMPTY_CHAT';

export const FEEDBACK_CHAT = 'FEEDBACK_CHAT';
export const FEEDBACK_CHAT_SUCCESS = 'FEEDBACK_CHAT_SUCCESS';
export const FEEDBACK_CHAT_FAIL = 'FEEDBACK_CHAT_FAIL';

/**
 * NOTIFICATION
 */
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const PUSH_NOTIFICATION_SUCCESS = 'PUSH_NOTIFICATION_SUCCESS';
export const PUSH_NOTIFICATION_FAIL = 'PUSH_NOTIFICATION_FAIL';

/**
 * VERIFY MAIL
 */
export const VERIFY_MAIL = 'VERIFY_MAIL';
export const VERIFY_MAIL_SUCCESS = 'VERIFY_MAIL_SUCCESS';
export const VERIFY_MAIL_FAIL = 'VERIFY_MAIL_FAIL';

/**
 * SEND VERIFICATION MAIL
 */
export const SEND_VERIFICATION_MAIL = 'SEND_VERIFICATION_MAIL';
export const SEND_VERIFICATION_MAIL_SUCCESS = 'SEND_VERIFICATION_MAIL_SUCCESS';
export const SEND_VERIFICATION_MAIL_FAIL = 'SEND_VERIFICATION_MAIL_FAIL';

/**
 * GET USER DETAIL
 */
export const GET_USER_DETAIL = 'GET_USER_DETAIL';
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';
export const GET_USER_DETAIL_FAIL = 'GET_USER_DETAIL_FAIL';
export const TOGGLE_NOTIFICATION = 'TOGGLE_NOTIFICATION';
export const TOGGLE_NOTIFICATION_FAIL = 'TOGGLE_NOTIFICATION_FAIL';
export const TOGGLE_NOTIFICATION_SUCCESS = 'TOGGLE_NOTIFICATION_SUCCESS';
/**
 * UPDATE USER DETAIL
 */
export const UPDATE_USER_DETAIL = 'UPDATE_USER_DETAIL';
export const UPDATE_USER_DETAIL_SUCCESS = 'UPDATE_USER_DETAIL_SUCCESS';
export const UPDATE_USER_DETAIL_FAIL = 'UPDATE_USER_DETAIL_FAIL';

/*  DEACTIVATE ACCOUNT */

export const DEACTIVATE_ACCOUNT = 'DEACTIVATE_ACCOUNT';
export const DEACTIVATE_ACCOUNT_SUCCESS = 'DEACTIVATE_ACCOUNT_SUCCESS';
export const DEACTIVATE_ACCOUNT_FAIL = 'DEACTIVATE_ACCOUNT_FAIL';

export const REASONS_LIST_DEACTIVATE = 'REASONS_LIST_DEACTIVATE';
export const REASONS_LIST_SUCCESS = 'REASONS_LIST_SUCCESS';
export const REASONS_LIST_FAIL = 'REASONS_LIST__FAIL';

/**
 * REPORT USER
 */
export const REPORT_USER = 'REPORT_USER';
export const REPORT_USER_SUCCESS = 'REPORT_USER_SUCCESS';
export const REPORT_USER_FAIL = 'REPORT_USER_FAIL';

/**
 * MESSAGE ID
 */
export const MESSAGE_ID_DETAIL = 'MESSAGE_ID_DETAIL';
export const MESSAGE_ID_DETAIL_CLEAR = 'MESSAGE_ID_DETAIL_CLEAR';
/**
 * DOCUMENT UPLOAD
 */

export const DOCUMENT_UPLOAD_PAYMENT = 'DOCUMENT_UPLOAD_PAYMENT';
export const DOCUMENT_UPLOAD = 'DOCUMENT_UPLOAD';
export const DOCUMENT_UPLOAD_SUCCESS = 'DOCUMENT_UPLOAD_SUCCESS';
export const DOCUMENT_UPLOAD_FAIL = 'DOCUMENT_UPLOAD_FAIL';
/**
 * DOCUMENT GET
 */

export const DOCUMENT_GET = 'DOCUMENT_GET';
export const DOCUMENT_GET_SUCCESS = 'DOCUMENT_GET_SUCCESS';
export const DOCUMENT_GET_FAIL = 'DOCUMENT_GET_FAIL';
/**
 * NEXT STEP
 */

export const NEXT_STEP = 'NEXT_STEP';
export const NEXT_STEP_SUCCESS = 'NEXT_STEP_SUCCESS';
export const NEXT_STEP_FAIL = 'NEXT_STEP_FAIL';
export const KYC_STATUS = {
  API: 'KYC_STATUS_API',
  START: 'KYC_STATUS_START',
  SUCCESS: 'KYC_STATUS_SUCCESS',
  FAIL: 'KYC_STATUS_FAIL',
  END: 'KYC_STATUS_END',
};
export const KYC_UPDATE = {
  KYC_UPDATE_API: 'KYC_UPDATE_API',
  START: 'KYC_UPDATE_START',
  SUCCESS: 'KYC_UPDATE_SUCCESS',
  FAIL: 'KYC_UPDATE_FAIL',
  END: 'KYC_UPDATE_END',
};
/**
 * Bank Update
 */

export const BANK_UPDATE = 'BANK_UPDATE';
export const BANK_UPDATE_SUCCESS = 'BANK_UPDATE_SUCCESS';
export const BANK_UPDATE_FAIL = 'BANK_UPDATE_FAIL';
/**
 * DOCUMENT GET
 */

export const ACCOUNT_STATUS = 'ACCOUNT_STATUS';
export const ACCOUNT_STATUS_SUCCESS = 'ACCOUNT_STATUS_SUCCESS';
export const ACCOUNT_STATUS_FAIL = 'ACCOUNT_STATUS_FAIL';
export const ACCOUNT_STATUS_CLEAN = 'ACCOUNT_STATUS_CLEAN';
/**
 * GET MATCH LIST
 */

export const GET_MATCH_LIST = 'GET_MATCH_LIST';
export const GET_MATCH_LIST_SUCCESS = 'GET_MATCH_LIST_SUCCESS';
export const GET_MATCH_LIST_FAIL = 'GET_MATCH_LIST_FAIL';
/**
 * GET Payment Request List
 */

export const GET_PAYMENT_REQUEST_LIST = 'GET_PAYMENT_REQUEST_LIST';
export const GET_PAYMENT_REQUEST_SUCCESS = 'GET_PAYMENT_REQUEST_SUCCESS';
export const GET_PAYMENT_REQUEST_FAIL = 'GET_PAYMENT_REQUEST_FAIL';
/**
 * GET Update Request Status
 */

export const UPDATE_REQUEST_STATUS = 'UPDATE_REQUEST_STATUS';
export const UPDATE_REQUEST_STATUS_SUCCESS = 'UPDATE_REQUEST_STATUS_SUCCESS';
export const UPDATE_REQUEST_STATUS_FAIL = 'UPDATE_REQUEST_STATUS_FAIL';

export const SEND_PAYMENT_REQUEST = 'SEND_PAYMENT_REQUEST';
export const SEND_PAYMENT_REQUEST_SUCCESS = 'SEND_PAYMENT_REQUEST_SUCCESS';
export const SEND_PAYMENT_REQUEST_FAIL = 'SEND_PAYMENT_REQUEST_FAIL';

export const TRANSACTION_HISTORY = 'TRANSACTION_HISTORY';
export const TRANSACTION_HISTORY_SUCCESS = 'TRANSACTION_HISTORY_SUCCESS';
export const TRANSACTION_HISTORY_FAIL = 'TRANSACTION_HISTORY_FAIL';
//Transfer Money
export const PAYMENT_TRANSFER = 'PAYMENT_TRANSFER';
export const PAYMENT_TRANSFER_SUCCESS = 'PAYMENT_TRANSFER_SUCCESS';
export const PAYMENT_TRANSFER_FAIL = 'PAYMENT_TRANSFER_FAIL';
// cancel Subscription
export const CANCEL_SUBSCRIPTION = 'CANCEL_SUBSCRIPTION';
export const CANCEL_SUBSCRIPTION_SUCCESS = 'CANCEL_SUBSCRIPTION_SUCCESS';
export const CANCEL_SUBSCRIPTION_FAIL = 'CANCEL_SUBSCRIPTION_FAIL';
// Transaction history pagionation
export const TRANSACTION_HISTORY_PAGE = 'TRANSACTION_HISTORY_PAGE';
export const TRANSACTION_HISTORY_PAGE_SUCCESS = 'TRANSACTION_HISTORY_PAGE_SUCCESS';
export const TRANSACTION_HISTORY_PAGE_FAIL = 'TRANSACTION_HISTORY_PAGE_FAIL';
