export const SET_THEME = 'SET_THEME';
export const LOADING_SPINNER = 'LOADING_SPINNER';
export const DISPATCH_LAT_LONG = 'DISPATCH_LAT_LONG';
export const DISPATCH_CURRENT_LOCATION = 'DISPATCH_CURRENT_LOCATION';
/**
 * Auth
 */
export const AUTH_CHECK = 'AUTH_CHECK';

export const AUTH_LOG_IN = 'AUTH_LOG_IN';
export const AUTH_LOG_IN_SUCCESS = 'AUTH_LOG_IN_SUCCESS';
export const AUTH_LOG_IN_FAIL = 'AUTH_LOG_IN_FAIL';

export const GET_GALLERY = 'GET_GALLERY';
export const GET_GALLERY_SUCCESS = 'GET_GALLERY_SUCCESS';
export const GET_GALLERY_FAIL = 'GET_GALLERY_FAIL';

// PTBDASHBOARD
export const PTB_DASHBOARD = 'PTB_DASHBOARD';
export const PTB_DASHBOARD_SUCCESS = 'PTB_DASHBOARD_SUCCESS';
export const PTB_DASHBOARD_FAIL = 'PTB_DASHBOARD_FAIL';

export const AUTH_MOBILE_NUMBER = 'AUTH_MOBILE_NUMBER';
export const AUTH_MOBILE_NUMBER_SUCCESS = 'AUTH_MOBILE_NUMBER_IN_SUCCESS';
export const AUTH_MOBILE_NUMBER_FAIL = 'AUTH_MOBILE_NUMBER_FAIL';

export const AUTH_VERIFY_OTP = 'AUTH_VERIFY_OTP';
export const AUTH_VERIFY_OTP_SUCCESS = 'AUTH_VERIFY_OTP_SUCCESS';
export const AUTH_VERIFY_OTP_FAIL = 'AUTH_VERIFY_OTP_FAIL';

export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
export const AUTH_LOG_OUT_SUCCESS = 'AUTH_LOG_OUT_SUCCESS';
export const AUTH_LOG_OUT_FAIL = 'AUTH_LOG_OUT_FAIL';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';

/**
 * SAVE BASIC DETAIL
 */
export const SAVE_BASIC_DETAIL = 'SAVE_BASIC_DETAIL';
export const SAVE_BASIC_DETAIL_SUCCESS = 'SAVE_BASIC_DETAIL_SUCCESS';
export const SAVE_BASIC_DETAIL_FAIL = 'SAVE_BASIC_DETAIL_FAIL';

/**
 * GET STATES
 */
export const GET_STATES_DETAIL = 'GET_STATES_DETAIL';
export const GET_STATES_SUCCESS = 'GET_STATES_SUCCESS';
export const GET_STATES_FAIL = 'GET_STATES_FAIL';
/**
 * GET PROFILE SETTER
 */
export const GET_PROFILE_SETTER_DETAIL = 'GET_PROFILE_SETTER_DETAIL';
export const GET_PROFILE_SETTER_SUCCESS = 'GET_PROFILE_SETTER_SUCCESS';
export const GET_PROFILE_SETTER_FAIL = 'GET_PROFILE_SETTER_FAIL';

/**
 * SET PREFERENCE
 */
export const SET_PREFERENCE = 'SET_PREFERENCE';
export const SET_PREFERENCE_SUCCESS = 'SET_PREFERENCE_SUCCESS';
export const SET_PREFERENCE_FAIL = 'SET_PREFERENCE_FAIL';

export const SET_USER = 'SET_USER';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_FAIL = 'SET_USER_FAIL';

/**
 * SEXUAL ORIENTATION
 */

export const GET_SEXUAL_ORIENTATION = 'GET_SEXUAL_ORIENTATION';
export const GET_SEXUAL_ORIENTATION_SUCCESS = 'GET_SEXUAL_ORIENTATION_SUCCESS';
export const GET_SEXUAL_ORIENTATION_FAIL = 'GET_SEXUAL_ORIENTATION_FAIL';

/**
 * DONOR PROFILE
 */

export const GET_DONOR_PROFILE_DETAIL = 'GET_DONOR_PROFILE_DETAIL';
export const GET_DONOR_PROFILE_SUCCESS = 'GET_DONOR_PROFILE_SUCCESS';
export const GET_DONOR_PROFILE_FAIL = 'GET_DONOR_PROFILE_FAIL';

/**
 * GET ATTRIBUTE
 */

export const GET_ATTRIBUTE = 'GET_ATTRIBUTE';
export const GET_ATTRIBUTE_SUCCESS = 'GET_ATTRIBUTE_SUCCESS';
export const GET_ATTRIBUTE_FAIL = 'GET_ATTRIBUTE_FAIL';

/**
 *  DELETE GALLERY
 */

export const GET_DELETE_GALLERY = 'GET_DELETE_GALLERY';
export const GET_DELETE_GALLERY_SUCCESS = 'GET_DELETE_GALLERY_SUCCESS';
export const GET_DELETE_GALLERY_FAIL = 'GET_DELETE_GALLERY_FAIL';

/**
 * SAVE ATTRIBUTE
 */

export const SAVE_ATTRIBUTE = 'SAVE_ATTRIBUTE';
export const SAVE_ATTRIBUTE_SUCCESS = 'SAVE_ATTRIBUTE_SUCCESS';
export const SAVE_ATTRIBUTE_FAIL = 'SAVE_ATTRIBUTE_FAIL';

/**
 * DONOR DASHBOARD
 */

export const DONOR_DASHBOARD = 'DONOR_DASHBOARD';
export const DONOR_DASHBOARD_SUCCESS = 'DONOR_DASHBOARD_SUCCESS';
export const DONOR_DASHBOARD_FAIL = 'DONOR_DASHBOARD_FAIL';

/**
 * PTB DETAILS
 */

export const PTB_DETAIL = 'PTB_DETAIL';
export const PTB_DETAIL_SUCCESS = 'PTB_DETAIL_SUCCESS';
export const PTB_DETAIL_FAIL = 'PTB_DETAIL_FAIL';
