export const SET_THEME = 'SET_THEME';
export const LOADING_SPINNER = 'LOADING_SPINNER';
export const DISPATCH_LAT_LONG = 'DISPATCH_LAT_LONG';
export const DISPATCH_CURRENT_LOCATION = 'DISPATCH_CURRENT_LOCATION';
/**
 * Auth
 */
export const AUTH_CHECK = 'AUTH_CHECK';

export const AUTH_LOG_IN = 'AUTH_LOG_IN';
export const AUTH_LOG_IN_SUCCESS = 'AUTH_LOG_IN_SUCCESS';
export const AUTH_LOG_IN_FAIL = 'AUTH_LOG_IN_FAIL';

///Device Register
export const DEVICE_REGISTER = 'DEVICE_REGISTER';
export const DEVICE_REGISTER_SUCCESS = 'DEVICE_REGISTER_SUCCESS';
export const DEVICE_REGISTER_FAIL = 'DEVICE_REGISTER_FAIL';

export const GET_GALLERY = 'GET_GALLERY';
export const GET_GALLERY_SUCCESS = 'GET_GALLERY_SUCCESS';
export const GET_GALLERY_FAIL = 'GET_GALLERY_FAIL';

// PTBDASHBOARD
export const PTB_DASHBOARD = 'PTB_DASHBOARD';
export const PTB_DASHBOARD_SUCCESS = 'PTB_DASHBOARD_SUCCESS';
export const PTB_DASHBOARD_FAIL = 'PTB_DASHBOARD_FAIL';

export const PTB_PROFILE_DETAIL = 'PTB_PROFILE_DETAIL';
export const PTB_PROFILE_DETAI_SUCCESS = 'PTB_PROFILE_DETAIL_SUCCESS';
export const PTB_PROFILE_DETAI_FAIL = 'PTB_PROFILE_DETAIL_FAIL';

export const AUTH_MOBILE_NUMBER = 'AUTH_MOBILE_NUMBER';
export const AUTH_MOBILE_NUMBER_SUCCESS = 'AUTH_MOBILE_NUMBER_IN_SUCCESS';
export const AUTH_MOBILE_NUMBER_FAIL = 'AUTH_MOBILE_NUMBER_FAIL';

export const AUTH_VERIFY_OTP = 'AUTH_VERIFY_OTP';
export const AUTH_VERIFY_OTP_SUCCESS = 'AUTH_VERIFY_OTP_SUCCESS';
export const AUTH_VERIFY_OTP_FAIL = 'AUTH_VERIFY_OTP_FAIL';

export const AUTH_LOG_OUT = 'AUTH_LOG_OUT';
export const AUTH_LOG_OUT_SUCCESS = 'AUTH_LOG_OUT_SUCCESS';
export const AUTH_LOG_OUT_FAIL = 'AUTH_LOG_OUT_FAIL';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';

/**
 * SAVE BASIC DETAIL
 */
export const SAVE_BASIC_DETAIL = 'SAVE_BASIC_DETAIL';
export const SAVE_BASIC_DETAIL_SUCCESS = 'SAVE_BASIC_DETAIL_SUCCESS';
export const SAVE_BASIC_DETAIL_FAIL = 'SAVE_BASIC_DETAIL_FAIL';

/**
 * INQUIRY FORM
 */

export const SUPPORT_FORM = 'SUPPORT_FORM';
export const SUPPORT_FORM_SUCCESS = 'SUPPORT_FORM_SUCCESS';
export const SUPPORT_FORM_FAIL = 'SUPPORT_FORM_FAIL';

/**
 * GET USER TYPE
 */

export const GET_USER_TYPE = 'GET_USER_TYPE';
export const GET_USER_TYPE_SUCCESS = 'GET_USER_TYPE_SUCCESS';
export const GET_USER_TYPE_FAIL = 'GET_USER_TYPE_FAIL';

/**
 * GET STATES
 */
export const GET_STATES_DETAIL = 'GET_STATES_DETAIL';
export const GET_STATES_SUCCESS = 'GET_STATES_SUCCESS';
export const GET_STATES_FAIL = 'GET_STATES_FAIL';
/**
 * GET PROFILE SETTER
 */
export const GET_PROFILE_SETTER_DETAIL = 'GET_PROFILE_SETTER_DETAIL';
export const GET_PROFILE_SETTER_SUCCESS = 'GET_PROFILE_SETTER_SUCCESS';
export const GET_PROFILE_SETTER_FAIL = 'GET_PROFILE_SETTER_FAIL';

/**
 * SET PREFERENCE
 */
export const SET_PREFERENCE = 'SET_PREFERENCE';
export const SET_PREFERENCE_SUCCESS = 'SET_PREFERENCE_SUCCESS';
export const SET_PREFERENCE_FAIL = 'SET_PREFERENCE_FAIL';

export const SET_USER = 'SET_USER';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_FAIL = 'SET_USER_FAIL';

/**
 * SAVE PREFERENCE
 */
export const SAVE_PREFERENCE = 'SAVE_PREFERENCE';
export const SAVE_PREFERENCE_SUCCESS = 'SAVE_PREFERENCE_SUCCESS';
export const SAVE_PREFERENCE_FAIL = 'SAVE_PREFERENCE_FAIL';

/**
 * SEXUAL ORIENTATION
 */

export const GET_SEXUAL_ORIENTATION = 'GET_SEXUAL_ORIENTATION';
export const GET_SEXUAL_ORIENTATION_SUCCESS = 'GET_SEXUAL_ORIENTATION_SUCCESS';
export const GET_SEXUAL_ORIENTATION_FAIL = 'GET_SEXUAL_ORIENTATION_FAIL';

/**
 * DONOR PROFILE
 */

export const GET_DONOR_PROFILE_DETAIL = 'GET_DONOR_PROFILE_DETAIL';
export const GET_DONOR_PROFILE_SUCCESS = 'GET_DONOR_PROFILE_SUCCESS';
export const GET_DONOR_PROFILE_FAIL = 'GET_DONOR_PROFILE_FAIL';

/**
 * GET ATTRIBUTE
 */

export const GET_ATTRIBUTE = 'GET_ATTRIBUTE';
export const GET_ATTRIBUTE_SUCCESS = 'GET_ATTRIBUTE_SUCCESS';
export const GET_ATTRIBUTE_FAIL = 'GET_ATTRIBUTE_FAIL';

/**
 *  DELETE GALLERY
 */

export const GET_DELETE_GALLERY = 'GET_DELETE_GALLERY';
export const GET_DELETE_GALLERY_SUCCESS = 'GET_DELETE_GALLERY_SUCCESS';
export const GET_DELETE_GALLERY_FAIL = 'GET_DELETE_GALLERY_FAIL';

/**
 * SAVE ATTRIBUTE
 */

export const SAVE_ATTRIBUTE = 'SAVE_ATTRIBUTE';
export const SAVE_ATTRIBUTE_SUCCESS = 'SAVE_ATTRIBUTE_SUCCESS';
export const SAVE_ATTRIBUTE_FAIL = 'SAVE_ATTRIBUTE_FAIL';

/**
 * DONOR DASHBOARD
 */

export const DONOR_DASHBOARD = 'DONOR_DASHBOARD';
export const DONOR_DASHBOARD_SUCCESS = 'DONOR_DASHBOARD_SUCCESS';
export const DONOR_DASHBOARD_FAIL = 'DONOR_DASHBOARD_FAIL';

/**
 * PTB DETAILS
 */

export const PTB_DETAIL = 'PTB_DETAIL';
export const PTB_DETAIL_SUCCESS = 'PTB_DETAIL_SUCCESS';
export const PTB_DETAIL_FAIL = 'PTB_DETAIL_FAIL';

/**
 * SM DONOR DETAILS
 */

export const SM_DONOR_DETAIL = 'SM_DONOR_DETAIL';
export const SM_DONOR_DETAIL_SUCCESS = 'SM_DONOR_DETAIL_SUCCESS';
export const SM_DONOR_DETAIL_FAIL = 'SM_DONOR_DETAIL_FAIL';

/**
 * UPDATE PROFILE
 */

export const UPDATE_PROFILE_IMG = 'UPDATE_PROFILE_IMG';
export const UPDATE_PROFILE_IMG_SUCCESS = 'UPDATE_PROFILE_IMG_SUCCESS';
export const UPDATE_PROFILE_IMG_FAIL = 'UPDATE_PROFILE_IMG_FAIL';

/**
 * UPDATE PROFILE
 */

export const SEND_LIKE_PTB = 'SEND_LIKE_PTB';
export const SEND_LIKE_PTB_SUCCESS = 'SEND_LIKE_PTB_SUCCESS';
export const SEND_LIKE_PTB_FAIL = 'SEND_LIKE_PTB_FAIL';

/**
 * CREATE AND GET  SUBSCRIPTION
 */

export const CREATE_SUBSCRIPTION = 'CREATE_SUBSCRIPTION';
export const SUBSCRIPTION_PLAN = 'SUBSCRIPTION_PLAN';
export const SUBSCRIPTION_STATUS = 'SUBSCRIPTION_STATUS';

export const CREATE_SUBSCRIPTION_SUCCESS = 'CREATE_SUBSCRIPTION_SUCCESS';
export const CREATE_SUBSCRIPTION_FAIL = 'CREATE_SUBSCRIPTION_FAIL';

export const SUBSCRIPTION_PLAN_SUCCESS = 'SUBSCRIPTION_PLAN_SUCCESS';
export const SUBSCRIPTION_PLAN_FAIL = 'SUBSCRIPTION_PLAN_FAIL';

export const SUBSCRIPTION_STATUS_SUCCESS = 'SUBSCRIPTION_STATUS_SUCCESS';
export const SUBSCRIPTION_STATUS_FAIL = 'SUBSCRIPTION_STATUS_FAIL';
 
/**
 * Profile Match
 */

export const PROFILE_MATCH = 'PROFILE_MATCH';
export const PROFILE_MATCH_SUCCESS = 'PROFILE_MATCH_SUCCESS';
export const PROFILE_MATCH_FAIL = 'PROFILE_MATCH_FAIL';
/**
 * Profile Match Response
 */
export const PROFILE_MATCH_RESPONSE = 'PROFILE_MATCH_RESPONSE';
export const PROFILE_MATCH_RESPONSE_SUCCESS = 'PROFILE_MATCH_RESPONSE_SUCCESS';
export const PROFILE_MATCH_RESPONSE_FAIL = 'PROFILE_MATCH_RESPONSE_FAIL';
/**
* CHAT
*/
export const PREPEND_CHAT = 'PREPEND_CHAT';
export const APPEND_CHAT = 'APPEND_CHAT';
export const EMPTY_CHAT = 'EMPTY_CHAT';
