import {Value} from '../../../constants/FixedValues';
import {Fonts} from '../../../constants/Constants';
import Colors from '../../../constants/Colors';
import Alignment from '../../../constants/Alignment';
import {
  dynamicSize,
  height,
  scaleWidth,
  statusHide,
} from '../../../utils/responsive';

export default {
  flex: {flex: 1, backgroundColor: Colors.BACKGROUND},
  mainContainer: {
    flex: Value.CONSTANT_VALUE_1,
    alignItems: Alignment.CENTER,
  },
  fixedheaderStyle: {marginRight: Value.CONSTANT_VALUE_20},
  lookingFor: {
    width: '100%',
    marginTop: Value.CONSTANT_VALUE_40,
  },
  lookingForText: {
    fontFamily: Fonts.OpenSansRegular,
    marginBottom: Value.CONSTANT_VALUE_17,
    fontSize: Value.CONSTANT_VALUE_14,
    lineHeight: Value.CONSTANT_VALUE_21,
  },
  required: {
    color: Colors.RED,
    fontSize: Value.CONSTANT_VALUE_18,
  },
  heightTextView: {
    fontFamily: Fonts.OpenSansBold,
    fontSize: Value.CONSTANT_VALUE_14,
    lineHeight: 21,
    letterSpacing: 0,
    color: Colors.BLACK_0,
  },
  containerView: {
    marginHorizontal: scaleWidth(40),
    backgroundColor: Colors.BACKGROUND,
    marginTop: statusHide(105),
  },
  label: {
    position: Alignment.ABSOLUTE,
    left: Value.CONSTANT_VALUE_0,
    zIndex: -1,
    color: Colors.LABEL_BLACK,
  },
  ageContainer: {
    flexDirection: Alignment.ROW,
    justifyContent: Alignment.SPACE_BETWEEN,
    flex: 1,
    marginLeft: Value.CONSTANT_VALUE_20,
  },
  ageContainerView: {
    flexDirection: Alignment.ROW,
    justifyContent: Alignment.SPACE_BETWEEN,
    flex: 1,
  },
  lookingsmDisabled: {
    alignItems: Alignment.CENTER,
    marginLeft: Value.CONSTANT_VALUE_10,
    fontFamily: Fonts.OpenSansBold,
    fontSize: Value.CONSTANT_VALUE_16,
    // marginBottom: Value.CONSTANT_VALUE_27,
    color: Colors.BLACK,
    opacity: 0.4,
    lineHeight: Value.CONSTANT_VALUE_21,
  },
  subscribeBtn: {
    marginLeft: 10,
    paddingHorizontal: 5,
    backgroundColor: Colors.COLOR_5ABCEC,
    borderRadius: 3,
    minHeight: 20,
    maxHeight: 30,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 0,
  },
  subscribeTxt: {
    color: Colors.WHITE,
    fontSize: 12,
  },
  lookingsm: {
    alignItems: Alignment.CENTER,
    marginLeft: Value.CONSTANT_VALUE_10,
    fontFamily: Fonts.OpenSansBold,
    fontSize: Value.CONSTANT_VALUE_16,
    // marginBottom: Value.CONSTANT_VALUE_27,
    color: Colors.BLACK,
    lineHeight: Value.CONSTANT_VALUE_21,
  },
  lookingDonor: {
    marginLeft: Value.CONSTANT_VALUE_10,
    fontWeight: Alignment.BOLD,
    fontSize: Value.CONSTANT_VALUE_16,
    marginBottom: Value.CONSTANT_VALUE_29,
  },
  lookingsDonor: {
    marginLeft: Value.CONSTANT_VALUE_10,
    fontWeight: Alignment.BOLD,
    fontSize: Value.CONSTANT_VALUE_16,
  },
  SDonorContainer: {
    flexDirection: Alignment.ROW,
    alignItems: Alignment.CENTER,
  },
  heightContainer: {
    flexDirection: Alignment.ROW,
    justifyContent: Alignment.SPACE_BETWEEN,
    paddingBottom: Value.CONSTANT_VALUE_10,
  },
  heightText: {
    color: Colors.RED,
    fontSize: Value.CONSTANT_VALUE_18,
  },
  chipText: {
    fontSize: Value.CONSTANT_VALUE_14,
    color: Colors.BLACK_0,
    marginTop: dynamicSize(Value.CONSTANT_VALUE_35),
    marginBottom: dynamicSize(Value.CONSTANT_VALUE_10),
    fontFamily: Fonts.OpenSansRegular,
  },
  chipsRequiredText: {
    color: Colors.RED,
    fontSize: Value.CONSTANT_VALUE_18,
  },
  hairContainer: {
    flexDirection: Alignment.ROW,
    flexWrap: 'wrap',
  },
  chips: {
    height: Value.CONSTANT_VALUE_41,
    width: Value.CONSTANT_VALUE_90,
    borderRadius: Value.CONSTANT_VALUE_21,
    justifyContent: Alignment.CENTER,
    marginRight: Value.CONSTANT_VALUE_9,
    marginVertical: Value.CONSTANT_VALUE_5,
  },
  eyeContainer: {
    flexDirection: Alignment.ROW,
    flexWrap: 'wrap',
    marginVerticle: Value.CONSTANT_VALUE_5,
    marginBottom: Value.CONSTANT_VALUE_20,
  },
  ageText: {
    marginVertical: Value.CONSTANT_VALUE_5,
    fontSize: Value.CONSTANT_VALUE_14,
    marginTop: Value.CONSTANT_VALUE_30,
    fontFamily: Fonts.OpenSansRegular,
    color: Colors.BLACK_0,
  },
  heightTextInner: {
    fontSize: Value.CONSTANT_VALUE_14,
    fontFamily: Fonts.OpenSansRegular,
    color: Colors.BLACK_0,
  },
  ageRangeChip: {
    height: Value.CONSTANT_VALUE_41,
    width: 98,
    borderRadius: Value.CONSTANT_VALUE_21,
    justifyContent: Alignment.CENTER,
    marginRight: Value.CONSTANT_VALUE_5,
    marginVertical: Value.CONSTANT_VALUE_10,
    padding: Value.CONSTANT_VALUE_0,
  },
  chipInsideText: {
    fontSize: 14,
    lineHeight: 21,
    letterSpacing: 0,
    alignSelf: Alignment.CENTER,
  },
  flexRow: {
    flexDirection: Alignment.ROW,
    alignItems: Alignment.CENTER,
    marginBottom: Value.CONSTANT_VALUE_27,
  },
  headerTxt: {
    color: Colors.RED,
    textDecorationLine: Alignment.UNDERLINE,
    fontFamily: Fonts.OpenSansBold,
    fontSize: Value.CONSTANT_VALUE_16,
  },
  Btn: {
    height: Value.CONSTANT_VALUE_80,
    width: Value.CONSTANT_VALUE_195,
    marginTop: 26,
    marginBottom: 78,
  },
  Btn2: {
    height: Value.CONSTANT_VALUE_80,
    marginTop: 26,
    marginBottom: 78,
  },
  header: {justifyContent: Alignment.FLEXEND},
  headerText: {
    textDecorationLine: Alignment.UNDERLINE,
    fontSize: Value.CONSTANT_VALUE_16,
    fontFamily: Fonts.OpenSansBold,
    color: Colors.RED,
    marginRight: 30,
  },
  heightlmt: {
    fontSize: Value.CONSTANT_VALUE_14,
    fontFamily: Fonts.OpenSansBold,
  },
  errMessage: {
    color: 'red',
    textAlign: Alignment.RIGHT,
    marginTop: Value.CONSTANT_VALUE_5,
    fontSize: Value.CONSTANT_VALUE_14,
    lineHeight: Value.CONSTANT_VALUE_21,
    textVerticleAlignment: Alignment.CENTER,
    fontFamily: Fonts.OpenSansRegular,
    position: 'absolute',
    bottom: -20,
    right: 0,
  },
  errLooking: {
    color: 'red',
    textAlign: Alignment.RIGHT,
    marginTop: Value.CONSTANT_VALUE_5,
    fontSize: Value.CONSTANT_VALUE_14,
    lineHeight: Value.CONSTANT_VALUE_21,
    textVerticleAlignment: Alignment.CENTER,
    fontFamily: Fonts.OpenSansRegular,
    position: 'absolute',
    bottom: 0,
    right: 0,
  },
  loaderContainer: {
    position: Alignment.ABSOLUTE,
    top: height / 2.5,
    alignSelf: Alignment.CENTER,
    width: Value.CONSTANT_VALUE_50,
    height: Value.CONSTANT_VALUE_50,
    alignItems: Alignment.CENTER,
    justifyContent: Alignment.CENTER,
    borderRadius: Value.CONSTANT_VALUE_35,
    backgroundColor: Colors.WHITE,
    zIndex: Value.CONSTANT_VALUE_999999,
  },
  changePlan: {
    backgroundColor: Colors.WHITE,
    paddingHorizontal: Value.CONSTANT_VALUE_20,
    paddingVertical: Value.CONSTANT_VALUE_15,
    borderWidth: Value.CONSTANT_VALUE_1,
    borderRadius: Value.CONSTANT_VALUE_10,
    marginTop: Value.CONSTANT_VALUE_20,
    flexDirection: Alignment.ROW,
    justifyContent: Alignment.SPACE_BETWEEN,
    borderColor: Colors.COLOR_5ABCEC,
    alignItems: Alignment.CENTER,
    flex: 1,
  },
  changePlanTxt: {
    fontSize: 14,
    fontFamily: Fonts.OpenSansBold,
    flex: 1,
  },
  disableing: {
    backgroundColor: Colors.CLEAR,
    width: '100%',
    height: '100%',
    position: Alignment.ABSOLUTE,
  },
};
